name: clue_player
description: A moderated safe app for curated content consumption.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Architecture
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  
  # Video Engine
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 
  
  # Utilities
  path_provider: ^2.1.5
  transparent_image: ^2.0.1
  intl: ^0.19.0
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  sqlite3: ^2.9.4
  drift: ^2.30.0
  path: ^1.9.1
  sqlite3_flutter_libs: ^0.5.41
  window_manager: ^0.5.1
  cryptography: ^2.9.0
  encrypt: ^5.0.3
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/clue_player.desktop
    - assets/images/empty_state.png
    - assets/images/logo.png
    - assets/images/noise_texture.jpg
    - assets/images/thumbnail_placeholder.jpg