name: clue_player
description: A moderated safe app for curated content consumption.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Architecture
  go_router: ^13.0.0
  google_fonts: ^6.1.0
  provider: ^6.1.1
  
  # Video Engine
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.4 
  
  # Utilities
  path_provider: ^2.1.2
  transparent_image: ^2.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/clue_player.desktop